spring.application.name=SpringDataJPADemo
#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=none
#"update" it will update the table after power on no data lost(not used in development)
#"create" it will remove the table after shutdown so data lost is there(not used in development)
#"create-drop" similar to "create"
#"validate" and "none" it is used in the development

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#it will wait till the hibernate creates the tables
spring.sql.init.mode=always
#it allow to run the queries in postgres db as well

jwt.secret=gweuywfwbifitulbweiufwyeruybfwueriwigfiuytf
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
#otherwise it will do inmemory caching and after the system off everything will vanis
